import React from 'react';
import {
  Database,
  Server,
  User,
  Cloud,
  Cpu,
  Globe,
  Shield,
  Code,
  FileText,
  Smartphone,
  Zap,
  Settings,
  Lock,
  Mail,
  HardDrive,
  Layers,
  Activity,
  Box,
  Terminal,
  Share2,
  Folder,
  Key,
  Users,
  Radio,
  Workflow,
  Wifi,
  Monitor,
  Laptop,
  Briefcase,
  Building,
  CreditCard,
  DollarSign,
  ShoppingCart,
  Tag,
  Phone,
  MapPin,
  Calendar,
  Clock,
  Target,
  Award,
  BarChart,
  PieChart,
  TrendingUp,
  Search,
  Filter,
  RefreshCw,
  Play,
  CheckCircle,
  AlertTriangle,
  Bookmark,
  Sparkles,
  Package,
  Compass,
  FileCode,
  FileSpreadsheet,
  Link,
  ShieldCheck,
  ZapOff
} from 'lucide-react';

export const ICON_LIST = [
  // Sunucular & Ağ (Tech & Infra)
  { id: 'server', label: 'Sunucu', icon: Server },
  { id: 'database', label: 'Veritabanı', icon: Database },
  { id: 'storage', label: 'Depolama / Disk', icon: HardDrive },
  { id: 'cpu', label: 'İşlemci / Microservice', icon: Cpu },
  { id: 'cloud', label: 'Bulut Servisi', icon: Cloud },
  { id: 'globe', label: 'Web / API Endpoint', icon: Globe },
  { id: 'wifi', label: 'Ağ / Wi-Fi', icon: Wifi },
  { id: 'network', label: 'Ağ / Proxy', icon: Share2 },
  { id: 'radio', label: 'Kuyruk / MQ', icon: Radio },
  { id: 'box', label: 'Container / Docker', icon: Box },

  // Güvenlik & Kod (Security & Dev)
  { id: 'shield', label: 'Güvenlik / Auth', icon: Shield },
  { id: 'shieldcheck', label: 'Onaylı Güvenlik', icon: ShieldCheck },
  { id: 'lock', label: 'Şifreleme', icon: Lock },
  { id: 'key', label: 'Anahtar / Token', icon: Key },
  { id: 'code', label: 'Kod / Script', icon: Code },
  { id: 'filecode', label: 'Kod Dosyası', icon: FileCode },
  { id: 'terminal', label: 'CLI / Worker', icon: Terminal },
  { id: 'workflow', label: 'Workflow', icon: Workflow },

  // Cihazlar & Arayüz (Devices & Clients)
  { id: 'monitor', label: 'Masaüstü / Monitör', icon: Monitor },
  { id: 'laptop', label: 'Dizüstü Bilgisayar', icon: Laptop },
  { id: 'phone', label: 'Mobil Uygulama', icon: Smartphone },
  { id: 'layers', label: 'Katman / Modül', icon: Layers },

  // Veri & Analitik (Data & BI)
  { id: 'barchart', label: 'Çubuk Grafik', icon: BarChart },
  { id: 'piechart', label: 'Pasta Grafik', icon: PieChart },
  { id: 'trendingup', label: 'Trend / Analiz', icon: TrendingUp },
  { id: 'activity', label: 'İzleme / Telemetri', icon: Activity },
  { id: 'file', label: 'Dosya / Doküman', icon: FileText },
  { id: 'spreadsheet', label: 'Tablo / Excel', icon: FileSpreadsheet },
  { id: 'folder', label: 'Dizin', icon: Folder },
  { id: 'search', label: 'Arama / Sorgu', icon: Search },
  { id: 'filter', label: 'Filtreleme', icon: Filter },

  // İş & Kullanıcılar (Business & People)
  { id: 'user', label: 'Kullanıcı', icon: User },
  { id: 'users', label: 'Kullanıcı Grubu', icon: Users },
  { id: 'briefcase', label: 'Şirket / İş', icon: Briefcase },
  { id: 'building', label: 'Kurum / Bina', icon: Building },
  { id: 'creditcard', label: 'Ödeme / Kredi Kartı', icon: CreditCard },
  { id: 'dollarsign', label: 'Finans / Para', icon: DollarSign },
  { id: 'shoppingcart', label: 'E-Ticaret / Sepet', icon: ShoppingCart },
  { id: 'tag', label: 'Etiket', icon: Tag },
  { id: 'mail', label: 'E-posta Servisi', icon: Mail },
  { id: 'map-pin', label: 'Konum / Lokasyon', icon: MapPin },
  { id: 'calendar', label: 'Takvim / Etkinlik', icon: Calendar },
  { id: 'clock', label: 'Zamanlayıcı / Cron', icon: Clock },
  { id: 'target', label: 'Hedef / KPI', icon: Target },

  // Durum & Araçlar (Status & Utilities)
  { id: 'zap', label: 'Event / Trigger', icon: Zap },
  { id: 'settings', label: 'Yapılandırma', icon: Settings },
  { id: 'sparkles', label: 'Yapay Zeka / AI', icon: Sparkles },
  { id: 'package', label: 'Paket / Modül', icon: Package },
  { id: 'compass', label: 'Navigasyon', icon: Compass },
  { id: 'link', label: 'Bağlantı / URL', icon: Link },
  { id: 'refreshcw', label: 'Yenileme / Döngü', icon: RefreshCw },
  { id: 'play', label: 'Başlatıcı / Runner', icon: Play },
  { id: 'checkcircle', label: 'Onaylı / Başarılı', icon: CheckCircle },
  { id: 'alerttriangle', label: 'Uyarı / Hata', icon: AlertTriangle },
  { id: 'bookmark', label: 'Yer İmi', icon: Bookmark },
];

export const getIconComponent = (iconId, props = {}) => {
  const item = ICON_LIST.find((i) => i.id === iconId?.toLowerCase());
  const Component = item ? item.icon : Box;
  return React.createElement(Component, props);
};
