import React from 'react';
import {
  // Infra & Database & Tech
  Database, Server, Cpu, Cloud, HardDrive, Terminal, Code, FileCode, Globe, Radio, Box, Share2, Wifi, Layers,
  Shield, Lock, Key, Router, Monitor, Laptop, Smartphone, Cable, Cast, DatabaseBackup, Gauge, Grid, KeyRound,
  LockKeyhole, Power, Printer, QrCode, RadioTower, Signal, WifiOff, Zap, ZapOff, Bot, Command, Hash, Wrench,

  // Data & Documents & Files
  FileText, Folder, File, BarChart, PieChart, TrendingUp, Activity, Search, Filter, Archive, Book, Bookmark,
  Clipboard, Copy, Edit, Feather, FileCheck, FilePlus, FileSpreadsheet, FolderPlus, Inbox, Library, Newspaper,
  Paperclip, Save, Trash, FileJson, FileQuestion,

  // Business, Finance & Users
  User, Users, UserCheck, UserPlus, UserX, Briefcase, Building, CreditCard, DollarSign, ShoppingCart, Tag,
  Mail, Phone, PhoneCall, MapPin, Calendar, Clock, Target, Award, Gift, ShoppingBag, Wallet, Coins, Landmark,
  Receipt, Scale, Trophy, Crown, BadgeCheck, Contact, Heart, ThumbsUp, Smile, Compass,

  // UI & Controls & Media
  Sliders, Workflow, RefreshCw, Play, Pause, CheckCircle, AlertTriangle, ShieldAlert, AlertCircle, Info, HelpCircle,
  Sparkles, Package, Link, ShieldCheck, Eye, Bell, Flame, Glasses, Headphones, Image, Mic, Moon, Sun, Music,
  Navigation, Pin, PlayCircle, RotateCcw, Send, Share, SlidersHorizontal, Speaker, Star, Tablet, Thermometer,
  Tv, Video, Volume2, Webcam, ZoomIn, Anchor, Camera, Clapperboard, Disc, Droplet, Film, Hammer, LifeBuoy,
  Lightbulb, Magnet, Map, MessageSquare, MousePointer, Scissors, Shuffle, Sidebar, Tent, Umbrella, Unlock,
  Upload, Voicemail, Watch, XCircle, Check, Plus, Minus, X, ChevronRight, ArrowUpRight
} from 'lucide-react';

export const ICON_LIST = [
  // --- ALTYAPI, SUNUCU & YAZILIM ---
  { id: 'server', label: 'Sunucu (Server)', icon: Server },
  { id: 'database', label: 'Veritabanı (Database)', icon: Database },
  { id: 'storage', label: 'Depolama (HardDrive)', icon: HardDrive },
  { id: 'cpu', label: 'İşlemci / Microservice (Cpu)', icon: Cpu },
  { id: 'cloud', label: 'Bulut (Cloud)', icon: Cloud },
  { id: 'globe', label: 'Web / API (Globe)', icon: Globe },
  { id: 'wifi', label: 'Wi-Fi Ağ', icon: Wifi },
  { id: 'network', label: 'Ağ / Proxy (Share2)', icon: Share2 },
  { id: 'radio', label: 'Kuyruk / Broker (Radio)', icon: Radio },
  { id: 'box', label: 'Container / Docker (Box)', icon: Box },
  { id: 'bot', label: 'Yapay Zeka Bot (Bot)', icon: Bot },
  { id: 'terminal', label: 'Terminal / CLI', icon: Terminal },
  { id: 'code', label: 'Kod (Code)', icon: Code },
  { id: 'filecode', label: 'Kod Dosyası (FileCode)', icon: FileCode },
  { id: 'workflow', label: 'İş Akışı (Workflow)', icon: Workflow },
  { id: 'cable', label: 'Kablo Entegrasyonu', icon: Cable },
  { id: 'cast', label: 'Yayın (Cast)', icon: Cast },
  { id: 'gauge', label: 'Performans (Gauge)', icon: Gauge },
  { id: 'grid', label: 'Izgara (Grid)', icon: Grid },
  { id: 'command', label: 'Komut (Command)', icon: Command },
  { id: 'hash', label: 'Hash / Tag', icon: Hash },
  { id: 'wrench', label: 'Bakım / Araçlar', icon: Wrench },

  // --- GÜVENLİK & KİMLİK DOĞRULAMA ---
  { id: 'shield', label: 'Güvenlik (Shield)', icon: Shield },
  { id: 'shieldcheck', label: 'Onaylı Güvenlik', icon: ShieldCheck },
  { id: 'shieldalert', label: 'Güvenlik Uyarısı', icon: ShieldAlert },
  { id: 'lock', label: 'Kilit / Şifreleme', icon: Lock },
  { id: 'lockkeyhole', label: 'Kilit Anahtarı', icon: LockKeyhole },
  { id: 'unlock', label: 'Kilit Açık', icon: Unlock },
  { id: 'key', label: 'Anahtar (Key)', icon: Key },
  { id: 'keyround', label: 'Erişim Anahtarı', icon: KeyRound },

  // --- CİHAZLAR & DONANIM ---
  { id: 'monitor', label: 'Masaüstü (Monitor)', icon: Monitor },
  { id: 'laptop', label: 'Dizüstü (Laptop)', icon: Laptop },
  { id: 'phone', label: 'Mobil (Smartphone)', icon: Smartphone },
  { id: 'tablet', label: 'Tablet', icon: Tablet },
  { id: 'tv', label: 'Ekran / TV', icon: Tv },
  { id: 'webcam', label: 'Kamera / Webcam', icon: Webcam },
  { id: 'printer', label: 'Yazıcı (Printer)', icon: Printer },
  { id: 'watch', label: 'Akıllı Saat', icon: Watch },

  // --- VERİ, DOKÜMAN & BİLGİ ---
  { id: 'barchart', label: 'Çubuk Grafik', icon: BarChart },
  { id: 'piechart', label: 'Pasta Grafik', icon: PieChart },
  { id: 'trendingup', label: 'Trend / Artış', icon: TrendingUp },
  { id: 'activity', label: 'Metrik (Activity)', icon: Activity },
  { id: 'file', label: 'Doküman (File)', icon: FileText },
  { id: 'filecheck', label: 'Onaylı Dosya', icon: FileCheck },
  { id: 'fileplus', label: 'Yeni Dosya', icon: FilePlus },
  { id: 'filejson', label: 'JSON Dosyası', icon: FileJson },
  { id: 'spreadsheet', label: 'Excel / Tablo', icon: FileSpreadsheet },
  { id: 'folder', label: 'Dizin (Folder)', icon: Folder },
  { id: 'folderplus', label: 'Yeni Dizin', icon: FolderPlus },
  { id: 'archive', label: 'Arşiv', icon: Archive },
  { id: 'inbox', label: 'Gelen Kutusu', icon: Inbox },
  { id: 'clipboard', label: 'Pano (Clipboard)', icon: Clipboard },
  { id: 'save', label: 'Kaydet (Save)', icon: Save },
  { id: 'copy', label: 'Kopyala', icon: Copy },
  { id: 'edit', label: 'Düzenle (Edit)', icon: Edit },
  { id: 'search', label: 'Arama (Search)', icon: Search },
  { id: 'filter', label: 'Filtre (Filter)', icon: Filter },

  // --- İŞ, FİNANS & KURUM ---
  { id: 'user', label: 'Kullanıcı (User)', icon: User },
  { id: 'users', label: 'Kullanıcılar', icon: Users },
  { id: 'usercheck', label: 'Onaylı Kullanıcı', icon: UserCheck },
  { id: 'userplus', label: 'Kullanıcı Ekle', icon: UserPlus },
  { id: 'userx', label: 'Engelli Kullanıcı', icon: UserX },
  { id: 'contact', label: 'Rehber / Kişi', icon: Contact },
  { id: 'briefcase', label: 'Şirket (Briefcase)', icon: Briefcase },
  { id: 'building', label: 'Bina / Kurum', icon: Building },
  { id: 'landmark', label: 'Banka / Kurum', icon: Landmark },
  { id: 'creditcard', label: 'Kredi Kartı', icon: CreditCard },
  { id: 'dollarsign', label: 'Finans (Dollar)', icon: DollarSign },
  { id: 'coins', label: 'Madeni Para', icon: Coins },
  { id: 'wallet', label: 'Cüzdan', icon: Wallet },
  { id: 'receipt', label: 'Fatura / Makbuz', icon: Receipt },
  { id: 'shoppingcart', label: 'Sepet (Cart)', icon: ShoppingCart },
  { id: 'shoppingbag', label: 'Alışveriş Çantası', icon: ShoppingBag },
  { id: 'tag', label: 'Etiket (Tag)', icon: Tag },
  { id: 'mail', label: 'E-posta (Mail)', icon: Mail },
  { id: 'phonecall', label: 'Arama / Telefon', icon: PhoneCall },
  { id: 'map-pin', label: 'Konum / Pin', icon: MapPin },
  { id: 'calendar', label: 'Takvim', icon: Calendar },
  { id: 'clock', label: 'Saat / Zaman', icon: Clock },
  { id: 'target', label: 'Hedef (Target)', icon: Target },
  { id: 'award', label: 'Ödül (Award)', icon: Award },
  { id: 'trophy', label: 'Kupa (Trophy)', icon: Trophy },
  { id: 'crown', label: 'Taç (Crown)', icon: Crown },
  { id: 'gift', label: 'Hediye (Gift)', icon: Gift },
  { id: 'scale', label: 'Hukuk / Adalet', icon: Scale },

  // --- MEDYA, İLETİŞİM & DİĞER (100+) ---
  { id: 'zap', label: 'Tetikleyici (Zap)', icon: Zap },
  { id: 'zapoff', label: 'Devre Dışı Zap', icon: ZapOff },
  { id: 'settings', label: 'Ayar (Settings)', icon: Settings },
  { id: 'sliders', label: 'Kaydırıcı (Sliders)', icon: Sliders },
  { id: 'sparkles', label: 'Yapay Zeka (AI)', icon: Sparkles },
  { id: 'package', label: 'Paket / Modül', icon: Package },
  { id: 'compass', label: 'Pusula / Yön', icon: Compass },
  { id: 'link', label: 'Bağlantı (Link)', icon: Link },
  { id: 'refreshcw', label: 'Döngü / Yenile', icon: RefreshCw },
  { id: 'rotateccw', label: 'Geri Döndür', icon: RotateCcw },
  { id: 'play', label: 'Oynat / Çalıştır', icon: Play },
  { id: 'pause', label: 'Duraklat', icon: Pause },
  { id: 'checkcircle', label: 'Başarılı (Check)', icon: CheckCircle },
  { id: 'alerttriangle', label: 'Uyarı (Warning)', icon: AlertTriangle },
  { id: 'alertcircle', label: 'Hata Dairesi', icon: AlertCircle },
  { id: 'info', label: 'Bilgi (Info)', icon: Info },
  { id: 'helpcircle', label: 'Yardım', icon: HelpCircle },
  { id: 'bookmark', label: 'Kayıtlı (Bookmark)', icon: Bookmark },
  { id: 'bell', label: 'Bildirim (Bell)', icon: Bell },
  { id: 'flame', label: 'Popüler (Flame)', icon: Flame },
  { id: 'heart', label: 'Favori (Heart)', icon: Heart },
  { id: 'thumbsup', label: 'Beğeni', icon: ThumbsUp },
  { id: 'smile', label: 'Tepki (Smile)', icon: Smile },
  { id: 'star', label: 'Yıldız (Star)', icon: Star },
  { id: 'eye', label: 'Görünürlük (Eye)', icon: Eye },
  { id: 'camera', label: 'Fotoğraf Kamerası', icon: Camera },
  { id: 'film', label: 'Video Filmi', icon: Film },
  { id: 'video', label: 'Kamera / Video', icon: Video },
  { id: 'image', label: 'Görsel / Resim', icon: Image },
  { id: 'music', label: 'Müzik / Ses', icon: Music },
  { id: 'headphones', label: 'Kulaklık', icon: Headphones },
  { id: 'speaker', label: 'Hoparlör', icon: Speaker },
  { id: 'mic', label: 'Mikrofon', icon: Mic },
  { id: 'message', label: 'Mesaj / Sohbet', icon: MessageSquare },
  { id: 'send', label: 'Gönder (Send)', icon: Send },
  { id: 'share', label: 'Paylaş (Share)', icon: Share },
  { id: 'sun', label: 'Güneş / Gündüz', icon: Sun },
  { id: 'moon', label: 'Gece / Ay', icon: Moon },
  { id: 'droplet', label: 'Damla / Su', icon: Droplet },
  { id: 'thermometer', label: 'Sıcaklık', icon: Thermometer },
  { id: 'umbrella', label: 'Şemsiye / Koruma', icon: Umbrella },
  { id: 'anchor', label: 'Çapa / Sabit', icon: Anchor },
  { id: 'map', label: 'Harita (Map)', icon: Map },
  { id: 'navigation', label: 'Navigasyon', icon: Navigation },
  { id: 'mouse', label: 'İmleç / Fare', icon: MousePointer },
  { id: 'scissors', label: 'Makas / Kes', icon: Scissors },
  { id: 'lightbulb', label: 'Fikir (Lightbulb)', icon: Lightbulb },
  { id: 'lifebuoy', label: 'Destek (Lifebuoy)', icon: LifeBuoy },
  { id: 'magnet', label: 'Mıknatıs', icon: Magnet },
  { id: 'hammer', label: 'Çekiç / Yapı', icon: Hammer },
  { id: 'paperclip', label: 'Ataş / Ek', icon: Paperclip },
  { id: 'pin', label: 'Sabitle (Pin)', icon: Pin },
  { id: 'power', label: 'Güç / Aç-Kapa', icon: Power },
  { id: 'qrcode', label: 'QR Kodu', icon: QrCode },
  { id: 'radiotower', label: 'Yayın Kulesi', icon: RadioTower },
  { id: 'signal', label: 'Sinyal Gücü', icon: Signal },
  { id: 'shuffle', label: 'Karıştır (Shuffle)', icon: Shuffle },
  { id: 'sidebar', label: 'Yan Panel', icon: Sidebar },
  { id: 'tent', label: 'Kamp / Çadır', icon: Tent },
  { id: 'upload', label: 'Yükle (Upload)', icon: Upload },
  { id: 'voicemail', label: 'Sesli Mesaj', icon: Voicemail },
  { id: 'xcircle', label: 'Kapat (X Circle)', icon: XCircle },
  { id: 'check', label: 'Onay (Check)', icon: Check },
  { id: 'plus', label: 'Ekle (Plus)', icon: Plus },
  { id: 'minus', label: 'Çıkar (Minus)', icon: Minus },
  { id: 'x', label: 'Çarpı (X)', icon: X },
  { id: 'chevronright', label: 'Sağ Ok', icon: ChevronRight },
  { id: 'arrowupright', label: 'Yön Oku', icon: ArrowUpRight }
];

export const getIconComponent = (iconId, props = {}) => {
  const item = ICON_LIST.find((i) => i.id === iconId?.toLowerCase());
  const Component = item ? item.icon : Box;
  return React.createElement(Component, props);
};
